version: "3"
services:
  redis:
    image: bitnami/redis:latest
    tty: true
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local

